### ISSUE TITLE
Cwiczenia 2

### ISSUE THREAD

**Issue by kudkudak** [gmum/ml2017#1]
Pomysly:

1. Wyjscie od gaussow do regresji liniowej/logistyczna (wykład)
2. Pokazanie ze regresja liniowa/logistyczna potrafi "zapamietac" dowolny zbior odpowiednio malo wymiarowy
3. Pokazanie wpływu regularyzacji na przewidywanie (trzeba wprowadzic splity)
4. Pokazanie co robi dokladnie na CIFAR10/MNIST i jak można oszukać  model (http://karpathy.github.io/2015/03/30/breaking-convnets/)

**Comment by kudkudak** [comment]
Fajnie by było sprzedać idee, ze prawie wszystko o co chodzi w ML (a przynajmniej w życiowym ML) to znaleźć takie cechy, że model liniowy sobie dobrze radzi. Idealnie jakby Ci się chciało sciagnac skads cechy MNISTa lepsze i pokazać ze model liniowy wywala 99.1% dzięki temu.

**Comment by lejlot** [comment]
uwazam ze to jest bardzo zla intuicja.
moge postawic arbitralnie duzo podobnych, np ze caly ml to szukanie takich
cech ze argmax z nich rozwiazuje klasyfikacje. jest masa modeli ktora nie
ma modelu liniowego jako budulca co wiecej taki argument sie trywializuje
bo jesli rozwiaze problem X to istnieje liniowa transformacja w rozwiazanie
X, nazywamy ja identycznoscia.

**Comment by kudkudak** [comment]
:+1: To prawda, ze to klamstwo :) Jesli mam to mowic precyzyjnie, to mozna powiedziec, ze chodzi w wiekszosci praktycznych problemow supervised na iid danych o znalezienie takich cech, ze prosty model sobie na nich dobrze radzi. Przykladem bedzie sytuacja jak napisalem powyzej, i taka intuicje proponuje sprzedac, probujac po drodze nie klamac :P

**Comment by kudkudak** [comment]
![image](https://cloud.githubusercontent.com/assets/1571945/23367232/cb0bfbac-fd09-11e6-94fa-a6543960986a.png)

![image](https://cloud.githubusercontent.com/assets/1571945/23367233/cd4e6256-fd09-11e6-9e43-80dc1d11ab00.png)

<- to do pokazania efektu reg na mniscie

**Comment by lejlot** [comment]
uwazam ze rozroznienie miedzy cecha a wynikiem jest sztuczne i stad sie
bierze problem

**Comment by kudkudak** [comment]
Mysle, ze warto wprowadzic model liniowy, zrobic jakies proste cwiczenie na tablicy z niego, potem polaczyc go z tym co bylo na wykladzie (Gaussy), a na końcu przejsc moze na szybko jak zmienia go regularyzacja? Ewentualnie mozna porysowac rozkłady p(w|x) (nawet samplujac monte carlo).
